import { ArrowRight, Clock, Mail, MapPin, Phone, ShieldCheck, Star } from "lucide-react";
import { SiteShell } from "@/components/site/SiteShell";
import { QuoteForm } from "@/components/site/QuoteForm";
import { SERVICE_AREAS, SITE } from "@/components/site/Brand";
import { Container, Eyebrow, PrimaryCta, Reveal, SectionHeading } from "@/components/site/ui";

export default function ContactPage() {
  return (
    <SiteShell>
      <section className="bg-foreground py-20 sm:py-28"><Container className="grid gap-12 lg:grid-cols-2 lg:gap-16"><div><Eyebrow className="text-primary-foreground/80">Free, no-obligation quotes</Eyebrow><h1 className="mt-3 text-4xl font-semibold tracking-tight text-background text-balance sm:text-5xl">Let’s talk about your property</h1><p className="mt-5 max-w-md text-base leading-relaxed text-background/70 sm:text-lg">Tell us what your lawn, driveway, or seasonal plan needs. We’ll get back to you within 24 hours — usually sooner.</p><ul className="mt-10 space-y-5"><li className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-md bg-background/10 text-primary-foreground"><Phone className="size-5" /></span><div><p className="text-xs uppercase tracking-wider text-background/50">Call anytime</p><a href={`tel:${SITE.phoneRaw}`} className="text-base font-semibold text-background hover:text-primary-foreground">{SITE.phone}</a></div></li><li className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-md bg-background/10 text-primary-foreground"><Mail className="size-5" /></span><div><p className="text-xs uppercase tracking-wider text-background/50">Email</p><a href={`mailto:${SITE.email}`} className="text-base font-semibold text-background hover:text-primary-foreground">{SITE.email}</a></div></li><li className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-md bg-background/10 text-primary-foreground"><MapPin className="size-5" /></span><div><p className="text-xs uppercase tracking-wider text-background/50">Based in</p><p className="text-base font-semibold text-background">Winnipeg, Manitoba</p></div></li><li className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-md bg-background/10 text-primary-foreground"><Clock className="size-5" /></span><div><p className="text-xs uppercase tracking-wider text-background/50">Hours</p><p className="text-base font-semibold text-background">Available 24/7</p></div></li></ul></div><Reveal delay={0.1}><div className="rounded-lg bg-background p-6 shadow-soft-lg sm:p-8"><QuoteForm id="contact-quote" variant="plain" /></div></Reveal></Container></section>

      <section className="bg-background py-20 sm:py-28"><Container className="grid items-start gap-12 lg:grid-cols-12"><div className="lg:col-span-5"><SectionHeading eyebrow="Where we work" title="Serving Winnipeg and the surrounding area" description={`Home base at ${SITE.address}. We bring the same friendly service and clean finish to homes across the city.`} /><a href={SITE.mapsUrl} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:text-primary/80">Open in Google Maps <ArrowRight className="size-4" /></a><div className="mt-8 flex items-center gap-2 rounded-md bg-secondary p-3 text-xs"><ShieldCheck className="size-5 text-primary" /><span><span className="block font-bold">Fully licensed & insured.</span><span className="text-muted-foreground">$2M general liability + WSIB coverage.</span></span></div><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><span className="flex gap-0.5">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className="size-3 fill-primary text-primary" />)}</span>{SITE.rating}★ average · {SITE.reviewCount}+ Winnipeg reviews</div></div><div className="lg:col-span-7"><div className="min-h-[360px] overflow-hidden rounded-lg border border-foreground/5 bg-secondary shadow-soft"><iframe title="ND Gill Lawn Care Services — Winnipeg, MB location" src={`https://www.google.com/maps?q=${encodeURIComponent(SITE.address)}&hl=en&z=14&output=embed`} width="100%" height="100%" style={{ border: 0, minHeight: 360 }} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /></div></div><div className="lg:col-span-12"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Service area</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{SERVICE_AREAS.map((area) => <div key={area} className="flex items-center gap-3 rounded-md border border-foreground/5 bg-secondary/45 px-4 py-3.5 transition-colors hover:border-primary/40"><span className="grid size-8 place-items-center rounded-full bg-accent text-primary"><MapPin className="size-4" /></span><span className="text-sm font-medium">{area}</span></div>)}</div></div></Container></section>

      <section className="bg-secondary py-20 sm:py-24"><Container className="flex flex-col items-center text-center"><Eyebrow>Same friendly service either way</Eyebrow><h2 className="mt-3 text-3xl font-semibold tracking-tight text-balance sm:text-4xl">Prefer to chat? Give us a ring.</h2><p className="mt-4 text-muted-foreground">Real local people, real local answers.</p><PrimaryCta href="tel:+14319979237" className="mt-8">Call {SITE.phone}</PrimaryCta></Container></section>
    </SiteShell>
  );
}
