import { ArrowRight, Calendar, Check, Clock, DollarSign, Phone, Scissors, Snowflake, Trees, Wind } from "lucide-react";
import { SiteShell } from "@/components/site/SiteShell";
import { Photo } from "@/components/site/Photo";
import { QuoteForm } from "@/components/site/QuoteForm";
import { SITE } from "@/components/site/Brand";
import { Container, Eyebrow, PrimaryCta, Reveal, SectionHeading } from "@/components/site/ui";

const HOME_HERO = "https://images.unsplash.com/photo-1558904541-efa843a96f01";
const SERVICES = [
  { icon: Scissors, title: "Lawn Mowing", description: "Weekly, bi-weekly, or one-time cuts with sharp blades, clean lines, trimming, and blower cleanup.", details: ["Weekly or bi-weekly cuts", "Healthy mowing height", "Trim around trees, fences & beds", "Walks and driveways blown clean"], image: "https://images.pexels.com/photos/6728933/pexels-photo-6728933.jpeg", alt: "Lawn mowing service on a residential property" },
  { icon: Trees, title: "Trimming & Edging", description: "Crisp borders along the driveway, sidewalk, patio, and beds — including every spot a mower cannot reach.", details: ["Driveway and curb edging", "Sidewalk and patio edges", "Detail trim around trees & posts", "Garden bed touch-ups"], image: "https://images.pexels.com/photos/29288279/pexels-photo-29288279.jpeg", alt: "Trimming and edging landscaping service" },
  { icon: Snowflake, title: "Snow Removal", description: "Driveways, sidewalks, and front walks cleared with a snowblower or shovel, with salting available for high-traffic areas.", details: ["Per-visit clearing", "Seasonal contracts", "Driveway, walk and front entry", "De-icing / salting available"], image: "https://images.pexels.com/photos/6952452/pexels-photo-6952452.jpeg", alt: "Snow removal service clearing a walkway" },
  { icon: Wind, title: "Spring & Fall Cleanup", description: "A complete yard reset when the season turns, from dethatching and first cut to leaf removal and final mow.", details: ["Spring dethatch and raking", "Leaf removal and haul-away", "First and final mow", "Bed cleanup and edging"], image: "https://images.pexels.com/photos/33356825/pexels-photo-33356825.jpeg", alt: "Spring and fall yard cleanup service" },
  { icon: Calendar, title: "Seasonal Contracts", description: "Bundle summer mowing and winter snow clearing into one predictable monthly plan with one familiar crew.", details: ["Locked-in monthly pricing", "Automatic mowing + snow scheduling", "Priority storm response", "Same crew all year", "Cancel anytime"], image: HOME_HERO, alt: "Well-maintained residential yard for a seasonal care plan" },
];

const PROCESS = [
  ["01", "Request a quote", "Tell us about your property and which service you need."],
  ["02", "Get a clear plan", "We confirm the scope, timing, and straightforward pricing."],
  ["03", "We do the work", "Our local crew arrives on time and respects your property."],
  ["04", "Enjoy the result", "We clean up, check the details, and keep you covered all season."],
] as const;

export default function ServicesPage() {
  return (
    <SiteShell>
      <section className="bg-background py-20 sm:py-28"><Container><SectionHeading eyebrow="What we do" title="Lawn care and snow removal for Winnipeg homes" description="Pick what you need this season. Add or drop services any time — with clear pricing and no confusing packages." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{SERVICES.map((service, i) => <Reveal key={service.title} delay={(i % 5) * 0.05} className="group flex flex-col rounded-lg border border-foreground/5 bg-secondary/45 p-6 transition-all duration-300 hover:-translate-y-1 hover:border-foreground/10 hover:bg-background hover:shadow-soft"><span className="grid size-11 place-items-center rounded-md bg-accent text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground"><service.icon className="size-5" /></span><h2 className="mt-5 text-base font-semibold tracking-tight">{service.title}</h2><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{service.description}</p><a href="#featured-services" className="mt-5 inline-flex items-center gap-1.5 text-sm font-semibold text-foreground/65 group-hover:text-primary">View details <ArrowRight className="size-3.5" /></a></Reveal>)}</div></Container></section>

      <section id="featured-services" className="bg-secondary py-20 sm:py-28"><Container><SectionHeading eyebrow="Featured services" title="The details are what make the difference" description="Every visit is built around the small things: clean edges, protected property, and a crew that leaves the site better than they found it." /><div className="mt-14 space-y-20 lg:space-y-28">{SERVICES.map((service, i) => <article key={service.title} className="grid items-center gap-8 lg:grid-cols-12 lg:gap-12"><Reveal className={`lg:col-span-7 ${i % 2 === 1 ? "lg:order-2" : ""}`}><div className="relative"><Photo src={service.image} alt={service.alt} ratio="16/11" className="rounded-lg" imgClassName="transition-transform duration-700 hover:scale-[1.03]" /><span className="absolute bottom-4 left-4 grid size-11 place-items-center rounded-md bg-primary text-primary-foreground shadow-soft"><service.icon className="size-5" /></span></div></Reveal><Reveal delay={0.08} className={`lg:col-span-5 ${i % 2 === 1 ? "lg:order-1" : ""}`}><Eyebrow>Service {String(i + 1).padStart(2, "0")}</Eyebrow><h2 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">{service.title}</h2><p className="mt-4 text-base leading-relaxed text-muted-foreground">{service.description}</p><ul className="mt-6 grid gap-2.5 sm:grid-cols-2">{service.details.map((detail) => <li key={detail} className="flex items-start gap-2.5 text-sm font-medium text-foreground/80"><span className="grid size-5 place-items-center rounded-full bg-accent text-primary"><Check className="size-3" strokeWidth={3} /></span>{detail}</li>)}</ul><PrimaryCta href="/contact" className="mt-7">Request a quote</PrimaryCta></Reveal></article>)}</div></Container></section>

      <section className="bg-background py-20 sm:py-28"><Container><SectionHeading eyebrow="How it works" title="A clear process from quote to clean-up" description="No phone tag and no surprises — just a straightforward way to get reliable help at home." /><ol className="mt-14 grid gap-10 sm:grid-cols-2 lg:grid-cols-4">{PROCESS.map(([step, title, body], i) => <Reveal key={step} as="li" delay={i * 0.07} className="relative"><span className="grid size-14 place-items-center rounded-full border border-foreground/10 bg-background text-sm font-semibold tracking-tight text-primary">{step}</span><h3 className="mt-5 text-base font-semibold tracking-tight">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p></Reveal>)}</ol></Container></section>

      <section className="bg-foreground py-20 sm:py-28"><Container className="grid gap-12 lg:grid-cols-2 lg:gap-16"><div><Eyebrow className="text-primary-foreground/80">Free, no-obligation quotes</Eyebrow><h2 className="mt-3 text-3xl font-semibold tracking-tight text-background text-balance sm:text-4xl">Let’s talk about your property</h2><p className="mt-5 max-w-md text-base leading-relaxed text-background/70 sm:text-lg">Tell us what you need and get a clear quote from a local Winnipeg crew.</p><ul className="mt-10 space-y-5"><li className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-md bg-background/10 text-primary-foreground"><Phone className="size-5" /></span><div><p className="text-xs uppercase tracking-wider text-background/50">Call anytime</p><a href={`tel:${SITE.phoneRaw}`} className="text-base font-semibold text-background hover:text-primary-foreground">{SITE.phone}</a></div></li><li className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-md bg-background/10 text-primary-foreground"><Clock className="size-5" /></span><div><p className="text-xs uppercase tracking-wider text-background/50">Availability</p><p className="text-base font-semibold text-background">24/7 snow response</p></div></li><li className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-md bg-background/10 text-primary-foreground"><DollarSign className="size-5" /></span><div><p className="text-xs uppercase tracking-wider text-background/50">Pricing</p><p className="text-base font-semibold text-background">Lower rates, no surprises</p></div></li></ul></div><Reveal delay={0.1}><div className="rounded-lg bg-background p-6 shadow-soft-lg sm:p-8"><QuoteForm id="services-quote" variant="plain" /></div></Reveal></Container></section>
    </SiteShell>
  );
}
